import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const retroComputer = localFont({
  src: '../assets/fonts/retro_computer/retro_computer_personal_use.ttf',
  variable: '--font-retro-computer'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={retroComputer.className}>{children}</body>
    </html>
  );
}
